### ISSUE TITLE
failed to create depository with bc-cli due to tls cert verification failure

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-saas#42]
## Reproduce

1. create depository with bc-cli

```shell
bc-cli create depository --name bcdep --contentID uid1xxx --host https://bc-saas.172.22.96.209.nip.io --enable-auth
```

Error log

```text
creating untrusted depository without account endorsement
Error: expect code 200 got 401
Usage:
  bc-cli create depository [args] [flags]

Flags:
  -a, --account string       account to be used
      --contentID string     depository file ID
      --contentType string   depository file type (default "File")
  -h, --help                 help for depository
      --host string          host URL of depository server
      --name string          depository name
      --platform string      depository source platform (default "bestchains")
  -w, --wallet string        wallet path (default "/Users/bjwswang/.bestchains/wallet")

Global Flags:
      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files (no effect when -logtostderr=true)
      --client-id string                 oidc client id (default "bff-client")
      --client-secret string             oidc client secret (default "61324af0-1234-4f61-b110-ef57013267d6")
      --config string                    config file (default "$HOME/.bestchains/config")
      --enable-auth                      enable oidc auth
      --issuer-url string                issuer url for oidc (default "https://portal.172.22.96.209.nip.io/oidc")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory (no effect when -logtostderr=true)
      --log_file string                  If non-empty, use this log file (no effect when -logtostderr=true)
      --log_file_max_size uint           Defines the maximum size a log file can grow to (no effect when -logtostderr=true). Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --master-url string                master url (default "https://172.22.96.146:9443")
      --one_output                       If true, only write logs to their native severity level (vs also writing to each lower severity level; no effect when -logtostderr=true)
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files (no effect when -logtostderr=true)
      --stderrthreshold severity         logs at or above this threshold go to stderr when writing to files and stderr (no effect when -logtostderr=true or -alsologtostderr=false) (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

panic: expect code 200 got 401

goroutine 1 [running]:
main.main()
	/Users/bjwswang/go/github.com/bjwswang/bc-cli/cmd/bc-cli/main.go:102 +0x45
```

2.  Check the bc-saas log

```text
authority
E0619 10:18:59.466064       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:19:10.325931       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
I0619 10:19:13.725823       1 oidc.go:73] "try to get user"
I0619 10:19:13.726029       1 oidc.go:76] oidc get user failed, try to get user from k8s err oidc: authenticator not initialized ok false
E0619 10:19:13.729692       1 oidc.go:81] Unable to authenticate the request due to an error: invalid bearer token
[10.31.49.204]:48678  401  -  POST     /basic/putUntrustValue
E0619 10:19:18.829942       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:19:28.876350       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:19:39.708221       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:19:49.669510       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:19:59.474135       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:20:10.341555       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:20:18.829490       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
I0619 10:20:21.449496       1 oidc.go:73] "try to get user"
I0619 10:20:21.449620       1 oidc.go:76] oidc get user failed, try to get user from k8s err oidc: authenticator not initialized ok false
E0619 10:20:21.453266       1 oidc.go:81] Unable to authenticate the request due to an error: invalid bearer token
[10.31.49.204]:49958  401  -  POST     /basic/putUntrustValue
E0619 10:20:28.875171       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
E0619 10:20:39.726878       1 oidc.go:324] oidc authenticator: initializing plugin: Get "https://portal.172.22.96.209.nip.io/oidc/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**Comment by bjwswang** [comment]
certificate expired
